# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20160412_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
    ]
