# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_team_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default='nofin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='team_assigned',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
    ]
